// This file is automatically generated. Do not modify it manually.

const manifest = JSON.parse(`
{
    "id": "com.mattermost.plugin-post-reminder",
    "name": "Post Reminder",
    "description": "This plugin allows the user to reminded about posts.",
    "homepage_url": "https://github.com/haliax/mattermost-plugin-post-reminder",
    "support_url": "https://github.com/haliax/mattermost-plugin-post-reminder/issues",
    "release_notes_url": "https://github.com/haliax/mattermost-plugin-post-reminder/releases/tag/v0.2.0",
    "version": "0.2.0",
    "min_server_version": "6.5.0",
    "server": {
        "executables": {
            "linux-amd64": "server/dist/plugin-linux-amd64",
            "darwin-amd64": "server/dist/plugin-darwin-amd64",
            "windows-amd64": "server/dist/plugin-windows-amd64.exe"
        },
        "executable": ""
    },
    "webapp": {
        "bundle_path": "webapp/dist/main.js"
    },
    "settings_schema": {
        "header": "",
        "footer": "",
        "settings": []
    }
}
`);

export default manifest;
export const id = manifest.id;
export const version = manifest.version;
